id: P002951
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137786
  title: ཤང་ཤང་སྨན་རྫོང་།
  author: ''
  volumes:
    62411d3f9b564aad9ce1b58ed4a1eeac:
      image_group_id: I2PD17915
      title: ''
      volume_number: 1
      total_pages: 572
      base_file: v001.txt
